### ISSUE TITLE
Cloud Spanner: UNKNOWN: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact

### ISSUE THREAD

**Issue by MikielAgutu** [googleapis/java-spanner-jdbc#176] opened 2020-07-02 09:40 UTC
#### Environment details

Windows 10 Enterprise Version 1909 (OS Build 1863.657)
Java SDK 11
com.google.cloud:google-cloud-spanner-jdbc:jar:1.15.0

#### Steps to reproduce

Unknown. This occurs in the test project.

#### Code example

`driver.connect(url, props);`

#### Stack trace

```
2020-06-30 15:47:04.296  INFO [me-limited test] o.f.c.internal.license.VersionPrinter    : Flyway Master Edition 0-SNAPSHOT by Redgate
2020-06-30 15:47:04.312  WARN [me-limited test] o.f.c.i.s.classpath.ClassPathScanner     : Unable to resolve location classpath:db/migration. Note this warning will become an error in Flyway 7.

org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:cloudspanner://localhost:9010/projects/my-project-id/instances/test-instance/databases/testdb;usePlainText=true) for user '': UNKNOWN: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : null
Error Code : 2
Message    : UNKNOWN: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact


	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:65)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:76)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.clean(Flyway.java:309)
	at org.flywaydb.core.migration.MigrationTestCase.setUp(MigrationTestCase.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: UNKNOWN: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory.of(JdbcSqlExceptionFactory.java:208)
	at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:175)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:270)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:236)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	... 18 more
Caused by: com.google.cloud.spanner.SpannerException: UNKNOWN: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:210)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:56)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:150)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:93)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.<init>(GapicSpannerRpc.java:334)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:132)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:127)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:561)
	at com.google.cloud.spanner.SpannerOptions.getSpannerRpcV1(SpannerOptions.java:732)
	at com.google.cloud.spanner.SpannerImpl.<init>(SpannerImpl.java:110)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:122)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:117)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:541)
	at com.google.cloud.spanner.jdbc.SpannerPool.createSpanner(SpannerPool.java:298)
	at com.google.cloud.spanner.jdbc.SpannerPool.getSpanner(SpannerPool.java:236)
	at com.google.cloud.spanner.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:204)
	at com.google.cloud.spanner.jdbc.ConnectionOptions.getConnection(ConnectionOptions.java:567)
	at com.google.cloud.spanner.jdbc.AbstractJdbcConnection.<init>(AbstractJdbcConnection.java:59)
	at com.google.cloud.spanner.jdbc.JdbcConnection.<init>(JdbcConnection.java:49)
	at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:172)
	... 21 more
Caused by: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:60)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:270)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.cloud.spanner.v1.stub.GrpcSpannerStub.create(GrpcSpannerStub.java:220)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.<init>(GapicSpannerRpc.java:305)
	... 36 more

```

#### External references such as API reference guides

n/a

#### Any additional information below

We get this error when running our unit tests. Looks like some sort of dependency clash, but we have no idea where it's coming from. I'm sharing the output of `mvn dependency:tree`.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< com.boxfuse.flyway-master:flyway-core >----------------
[INFO] Building flyway-core 0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from [redacted]: https://[redacted]/repository/oracle/io/grpc/grpc-api/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-api/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
Downloading from [redacted]: https://[redacted]/repository/oracle/io/grpc/grpc-core/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
Downloading from [redacted]: https://[redacted]/repository/oracle/io/grpc/grpc-netty-shaded/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-netty-shaded/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ flyway-core ---
[WARNING] Failure to transfer io.grpc:grpc-api/maven-metadata.xml from https://[redacted]/repository/oracle was cached in the local repository, resolution will not be reattempted until the update interval of [redacted] has elapsed or updates are forced. Original error: Could not transfer metadata io.grpc:grpc-api/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
[WARNING] Failure to transfer io.grpc:grpc-core/maven-metadata.xml from https://[redacted]/repository/oracle was cached in the local repository, resolution will not be reattempted until the update interval of [redacted] has elapsed or updates are forced. Original error: Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
[WARNING] Failure to transfer io.grpc:grpc-netty-shaded/maven-metadata.xml from https://[redacted]/repository/oracle was cached in the local repository, resolution will not be reattempted until the update interval of [redacted] has elapsed or updates are forced. Original error: Could not transfer metadata io.grpc:grpc-netty-shaded/maven-metadata.xml from/to [redacted] (https://[redacted]/repository/oracle): Not authorized , ReasonPhrase:Unauthorized.
[INFO] com.boxfuse.flyway-master:flyway-core:jar:0-SNAPSHOT
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile (optional) 
[INFO] +- commons-logging:commons-logging:jar:1.2:compile (optional) 
[INFO] +- org.jboss:jboss-vfs:jar:3.2.15.Final:compile (optional) 
[INFO] |  \- org.jboss.logging:jboss-logging:jar:3.1.4.GA:compile (optional) 
[INFO] +- org.osgi:org.osgi.core:jar:4.3.1:provided (optional) 
[INFO] +- com.google.android:android:jar:4.0.1.2:compile (optional) 
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  +- org.khronos:opengl-api:jar:gl1.1-android-2.1_r1:compile (optional) 
[INFO] |  +- xerces:xmlParserAPIs:jar:2.6.2:compile (optional) 
[INFO] |  +- xpp3:xpp3:jar:1.1.4c:compile (optional) 
[INFO] |  \- org.json:json:jar:20080701:compile (optional) 
[INFO] +- org.postgresql:postgresql:jar:42.2.12.jre6:compile (optional) 
[INFO] +- org.springframework:spring-jdbc:jar:2.5.6:test
[INFO] |  +- org.springframework:spring-beans:jar:2.5.6:test
[INFO] |  +- org.springframework:spring-context:jar:2.5.6:test
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] |  +- org.springframework:spring-core:jar:2.5.6:test
[INFO] |  \- org.springframework:spring-tx:jar:2.5.6:test
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:test
[INFO] |  \- ch.qos.logback:logback-core:jar:1.2.3:test
[INFO] +- com.zaxxer:HikariCP:jar:2.7.9:test
[INFO] +- junit:junit:jar:4.13:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |  \- org.objenesis:objenesis:jar:2.1:test
[INFO] +- org.hsqldb:hsqldb:jar:2.5.0:test
[INFO] +- com.h2database:h2:jar:1.4.200:test
[INFO] +- com.google.cloud:google-cloud-spanner-jdbc:jar:1.15.0:test
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.17.0:test
[INFO] |  +- com.google.cloud:google-cloud-spanner:jar:1.52.0:test
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.27.2:test
[INFO] |  |  +- io.grpc:grpc-context:jar:1.27.2:test
[INFO] |  |  +- io.grpc:grpc-core:jar:1.27.2:test
[INFO] |  |  |  +- com.google.android:annotations:jar:4.1.1.4:test
[INFO] |  |  |  \- io.perfmark:perfmark-api:jar:0.19.0:test
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.27.2:test
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.27.2:test
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.27.2:test
[INFO] |  |  +- com.google.api.grpc:grpc-google-common-protos:jar:1.17.0:test
[INFO] |  |  +- com.google.api.grpc:proto-google-iam-v1:jar:0.13.0:test
[INFO] |  |  +- com.google.cloud:google-cloud-core-grpc:jar:1.93.2:test
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.26.0:test
[INFO] |  |  +- io.opencensus:opencensus-contrib-grpc-util:jar:0.26.0:test
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:jar:1.52.0:test
[INFO] |  |  +- com.google.api:gax-grpc:jar:1.54.0:test
[INFO] |  |  |  \- io.grpc:grpc-alts:jar:1.27.2:test
[INFO] |  |  |     +- io.grpc:grpc-grpclb:jar:1.27.2:test
[INFO] |  |  |     \- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:test
[INFO] |  |  \- javax.annotation:javax.annotation-api:jar:1.3.2:test
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.11.4:test
[INFO] |  +- com.google.guava:guava:jar:28.2-android:test
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.5:test
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:test
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:test
[INFO] |  +- com.google.api:gax:jar:1.54.0:test
[INFO] |  +- org.threeten:threetenbp:jar:1.4.1:test
[INFO] |  +- io.grpc:grpc-api:jar:1.27.2:test
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:test
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.27.2:test
[INFO] |  +- com.google.api:api-common:jar:1.8.1:test
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:test
[INFO] |  +- com.google.http-client:google-http-client:jar:1.34.2:test
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.24.0:test
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.20.0:test
[INFO] |  |  +- com.google.auto.value:auto-value-annotations:jar:1.7:test
[INFO] |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.34.0:test
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.10.1:test
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.93.3:test
[INFO] |  +- com.google.code.gson:gson:jar:2.8.6:test
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:0.20.0:test
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.5:test
[INFO] |  +- com.google.api.grpc:proto-google-cloud-spanner-v1:jar:1.52.0:test
[INFO] |  +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:jar:1.52.0:test
[INFO] |  \- com.google.protobuf:protobuf-java-util:jar:3.11.4:test
[INFO] +- org.apache.derby:derby:jar:10.15.2.0:test
[INFO] +- org.apache.derby:derbytools:jar:10.15.2.0:compile (optional) 
[INFO] +- org.apache.derby:derbyshared:jar:10.15.2.0:test
[INFO] +- net.snowflake:snowflake-jdbc:jar:3.11.1:test
[INFO] +- org.xerial:sqlite-jdbc:jar:3.30.1:test
[INFO] +- mysql:mysql-connector-java:jar:8.0.17:test
[INFO] +- org.firebirdsql.jdbc:jaybird-jdk18:jar:3.0.8:test
[INFO] |  +- javax.resource:connector-api:jar:1.5:test
[INFO] |  \- org.antlr:antlr4-runtime:jar:4.7:test
[INFO] +- org.mariadb.jdbc:mariadb-java-client:jar:2.6.0:test
[INFO] +- net.sourceforge.jtds:jtds:jar:1.3.1:test
[INFO] +- com.oracle.database.jdbc:ojdbc8:jar:19.6.0.0:test
[INFO] |  +- com.oracle.database.jdbc:ucp:jar:19.6.0.0:test
[INFO] |  +- com.oracle.database.security:oraclepki:jar:19.6.0.0:test
[INFO] |  +- com.oracle.database.security:osdt_cert:jar:19.6.0.0:test
[INFO] |  +- com.oracle.database.security:osdt_core:jar:19.6.0.0:test
[INFO] |  +- com.oracle.database.ha:simplefan:jar:19.6.0.0:test
[INFO] |  \- com.oracle.database.ha:ons:jar:19.6.0.0:test
[INFO] +- com.ibm.db2.jcc:db2jcc4:jar:10.1:test
[INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:7.2.0.jre8:test
[INFO] +- com.amazon.redshift.jdbc42:redshift:jar:1.2.10.1009:test
[INFO] +- com.sybase.ase:jconnect:jar:7.07:test
[INFO] +- com.sap.db.jdbc:ngdbc:jar:2.2.3:test
[INFO] \- com.ibm.informix:jdbc:jar:4.50.3:test
[INFO]    \- org.mongodb:bson:jar:3.8.0:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.864 s
[INFO] Finished at: 2020-07-02T10:29:32+01:00
[INFO] ------------------------------------------------------------------------

```

**Comment by olavloite** [comment] 2020-07-02 12:14
It seems that there is some sort of conflict between (this version of) the Cloud Spanner JDBC driver and `com.google.android:android:jar:4.0.1.2`. A simple test application using the following dependencies will cause the same error:

```xml
  <dependencies>
    <dependency>
      <groupId>com.google.android</groupId>
      <artifactId>android</artifactId>
      <version>4.0.1.2</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-spanner-jdbc</artifactId>
      <version>1.15.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

Removing the android dependency allows the test application to run without problems. I'll try to dig a little deeper to see if I can figure out exactly what is causing the conflict.

**Comment by olavloite** [comment] 2020-07-02 13:59
This problem is caused by this line: https://github.com/grpc/grpc-java/blob/c6bd97245c4bf21e423c5ee7740e9635ab8f1646/api/src/main/java/io/grpc/ServiceProviders.java#L61

If the `com.google.android:android:jar` is on the classpath, the gRPC libraries assume that the entire build is for Android. That again means that it expects certain channel providers to be present and to be used, which in this case is not true.

@MikielAgutu Am I right to assume that you include the Android library because you also support schema management of some internal Android database? And would it in some way be possible to make a split between the builds with and without Android?

I'm afraid that there is not very much we could do in the JDBC driver to prevent this error when the Android library is included.

**Comment by MikielAgutu** [comment] 2020-07-06 15:38
@olavloite We include the Android library because Flyway is designed to run on Android alongside desktop operating systems. Users deploy Flyway in many contexts and environments. We don't have much control over a particular deployment of Flyway.

This issue arises during automated test runs. We don't want to produce two versions of Flyway just to exclude a single dependency. I also can't see a way to perform a test run excluding the Android dependencies. Any ideas? I've tried setting `scope` to `provided` for instance.

**Comment by olavloite** [comment] 2020-07-10 16:10
@MikielAgutu I was looking into filing an issue with the core grpc libraries and was investigating what might be the best solution, and while doing that I found a workaround that should be less of a hassle. At least this works for my small test setup:

Adding the following test dependency in combination with the Android library and the JDBC driver works:

```xml
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <version>1.27.2</version>
      <scope>test</scope>
    </dependency>
```

The entire list of dependencies for the test setup that I have at the moment is as follows:

```xml
  <dependencies>
    <dependency>
      <groupId>com.google.android</groupId>
      <artifactId>android</artifactId>
      <version>4.0.1.2</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-spanner-jdbc</artifactId>
      <version>1.15.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <version>1.27.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

If I remove the `grpc-netty` dependency, I get the exact same error as you were running into. Adding it again makes it work, which is logical as it includes one of the hardcoded `ChannelProviders` to use in combination with Android.
The biggest hassle with this will be that you will need to keep the version of the `grpc-netty` test dependency in sync with the version of `grpc` that the JDBC driver is using.

Would you mind trying if that would solve the issue for you as well?

**Comment by olavloite** [comment] 2020-07-15 12:58
@MikielAgutu Would the above be a suitable workaround for you?

**Comment by DoodleBobBuffPants** [comment] 2020-08-27 10:57
We can confirm that adding `grpc-netty` as a dependency does fix it. Feel free to close this issue. Thank you:)

**Closed** 2020-08-27 14:46 UTC
Labels: api: spanner, type: question
